[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
chrono = "0.4.38"
crossbeam = "0.8.4"
env_logger = "0.11.3"
libbpf-rs = "0.23.0"
libbpf-sys = "1.4.0"
libc = "0.2.153"
log = "0.4.21"
procfs = "0.16.0"
